import type { AppLanguage } from "../types";

const copy = {
  "zh-TW": {
    title: "自訂 AI Provider",
    summary: "連接 Ollama 或自己的 OpenAI 相容 Gateway",
    aiDescription: "OpenRouter 適合快速使用雲端模型；Gemma 4 在本機執行；進階使用者也可以連接自己的 Gateway 或 Ollama。",
    advanced: "進階設定",
    configured: (count: number) => count ? `已設定 ${count} 個連線` : "尚未設定",
    description: "給熟悉模型服務的進階使用者。澄境只會把你主動送出的 AI 內容傳到這個位址。",
    localOnly: "遠端位址必須使用 HTTPS；HTTP 允許 localhost 或私有區域網路位址（例如 10.x、172.16-31.x、192.168.x）。API Key 會加密留在本機，不會放進備份。",
    ollama: "Ollama（本機）", gateway: "OpenAI 相容 Gateway", connectionName: "連線名稱", baseUrl: "API 位址", model: "模型 ID", apiKey: "API Key（選填）",
    keySaved: "已保存金鑰；不更換時，這格保持空白即可", keyOptional: "Ollama 通常不需要金鑰", save: "儲存連線", saving: "正在儲存…", test: "測試連線", testing: "正在測試…", models: "取得模型", select: "使用", active: "使用中", remove: "移除", newConnection: "新增連線", clearKey: "移除金鑰",
    saved: "連線已安全儲存。", connected: (count: number) => `連線正常，找到 ${count} 個模型。`, removed: "連線已移除。", chooseModel: "請先輸入模型 ID。", desktop: "請在澄境桌面版設定。",
  },
  "zh-CN": {
    title: "自定义 AI Provider", summary: "连接 Ollama 或自己的 OpenAI 兼容 Gateway", aiDescription: "OpenRouter 适合快速使用云端模型；Gemma 4 在本机运行；高级用户也可以连接自己的 Gateway 或 Ollama。", advanced: "高级设置", configured: (count: number) => count ? `已设置 ${count} 个连接` : "尚未设置", description: "面向熟悉模型服务的高级用户。澄境只会把你主动发送的 AI 内容传到这个地址。", localOnly: "远程地址必须使用 HTTPS；HTTP 允许这台电脑的 localhost 或私有局域网地址（例如 10.x、172.16-31.x、192.168.x）。API Key 会加密保存在本机，不会写入备份。", ollama: "Ollama（本机）", gateway: "OpenAI 兼容 Gateway", connectionName: "连接名称", baseUrl: "API 地址", model: "模型 ID", apiKey: "API Key（可选）", keySaved: "已保存密钥；不更换时，这一栏保持空白即可", keyOptional: "Ollama 通常不需要密钥", save: "保存连接", saving: "正在保存…", test: "测试连接", testing: "正在测试…", models: "获取模型", select: "使用", active: "使用中", remove: "移除", newConnection: "新增连接", clearKey: "移除密钥", saved: "连接已安全保存。", connected: (count: number) => `连接正常，找到 ${count} 个模型。`, removed: "连接已移除。", chooseModel: "请先输入模型 ID。", desktop: "请在澄境桌面版设置。",
  },
  en: {
    title: "Custom AI provider", summary: "Connect Ollama or your own OpenAI-compatible gateway", aiDescription: "Use OpenRouter for convenient cloud models, Gemma 4 on-device, or connect your own gateway or Ollama as an advanced option.", advanced: "Advanced", configured: (count: number) => count ? `${count} connection${count === 1 ? "" : "s"} configured` : "Not configured", description: "For advanced users who run model services. ChengJing sends only the AI content you explicitly submit to this address.", localOnly: "Remote URLs must use HTTPS; HTTP is allowed for localhost, loopback, private LAN IPs, or IPv6 ULA. API keys are encrypted locally and excluded from backups.", ollama: "Ollama (local)", gateway: "OpenAI-compatible gateway", connectionName: "Connection name", baseUrl: "API URL", model: "Model ID", apiKey: "API key (optional)", keySaved: "Key saved; leave this field empty unless replacing it", keyOptional: "Ollama usually needs no key", save: "Save connection", saving: "Saving…", test: "Test connection", testing: "Testing…", models: "Fetch models", select: "Use", active: "Active", remove: "Remove", newConnection: "New connection", clearKey: "Remove key", saved: "Connection saved securely.", connected: (count: number) => `Connected. Found ${count} model${count === 1 ? "" : "s"}.`, removed: "Connection removed.", chooseModel: "Enter a model ID first.", desktop: "Configure this in the ChengJing desktop app.",
  },
  ja: {
    title: "カスタムAI Provider", summary: "OllamaまたはOpenAI互換Gatewayに接続", aiDescription: "OpenRouterでクラウドモデルを手軽に使い、Gemma 4をローカルで実行し、上級者は独自GatewayやOllamaにも接続できます。", advanced: "詳細設定", configured: (count: number) => count ? `${count}件の接続を設定済み` : "未設定", description: "モデルサービスに詳しい方向けです。明示的に送信したAIコンテンツだけをこのURLへ送ります。", localOnly: "リモートURLはHTTPS必須です。HTTPはこのPCのlocalhostまたはプライベートLANアドレスのみ許可されます。API Keyはローカルで暗号化され、バックアップには含まれません。", ollama: "Ollama（ローカル）", gateway: "OpenAI互換Gateway", connectionName: "接続名", baseUrl: "API URL", model: "モデルID", apiKey: "API Key（任意）", keySaved: "キー保存済み。変更しない場合は空欄のままで構いません", keyOptional: "Ollamaは通常キー不要です", save: "接続を保存", saving: "保存中…", test: "接続テスト", testing: "テスト中…", models: "モデル取得", select: "使用", active: "使用中", remove: "削除", newConnection: "新しい接続", clearKey: "キーを削除", saved: "接続を安全に保存しました。", connected: (count: number) => `接続しました。${count}件のモデルが見つかりました。`, removed: "接続を削除しました。", chooseModel: "先にモデルIDを入力してください。", desktop: "ChengJingデスクトップ版で設定してください。",
  },
  ko: {
    title: "사용자 지정 AI Provider", summary: "Ollama 또는 OpenAI 호환 Gateway 연결", aiDescription: "OpenRouter로 클라우드 모델을 간편하게 사용하고, Gemma 4를 로컬에서 실행하거나 고급 옵션으로 자체 Gateway와 Ollama를 연결할 수 있습니다.", advanced: "고급 설정", configured: (count: number) => count ? `${count}개 연결 설정됨` : "설정되지 않음", description: "모델 서비스에 익숙한 고급 사용자를 위한 기능입니다. 사용자가 직접 전송한 AI 내용만 이 주소로 보냅니다.", localOnly: "원격 주소는 HTTPS여야 합니다. HTTP는 이 컴퓨터의 localhost 또는 사설 LAN 주소에서만 허용됩니다. API Key는 로컬에 암호화되며 백업에 포함되지 않습니다.", ollama: "Ollama(로컬)", gateway: "OpenAI 호환 Gateway", connectionName: "연결 이름", baseUrl: "API 주소", model: "모델 ID", apiKey: "API Key(선택)", keySaved: "키 저장됨. 변경하지 않으면 이 칸을 비워 두세요", keyOptional: "Ollama는 보통 키가 필요 없습니다", save: "연결 저장", saving: "저장 중…", test: "연결 테스트", testing: "테스트 중…", models: "모델 가져오기", select: "사용", active: "사용 중", remove: "삭제", newConnection: "새 연결", clearKey: "키 삭제", saved: "연결을 안전하게 저장했습니다.", connected: (count: number) => `연결되었습니다. ${count}개 모델을 찾았습니다.`, removed: "연결을 삭제했습니다.", chooseModel: "먼저 모델 ID를 입력하세요.", desktop: "ChengJing 데스크톱 앱에서 설정하세요.",
  },
} as const;

export function getAdvancedProviderCopy(language: AppLanguage) {
  return copy[language] || copy.en;
}

const diagnosticCopy = {
  "zh-TW": {
    title: "連線診斷",
    healthy: (model: string) => `連線與模型正常：${model}`,
    url: "網址格式或安全規則不正確。",
    connection: "無法建立連線，請確認服務、IP、連接埠與防火牆。",
    apiPath: "服務已回應，但 API 路徑不正確。請確認網址是否包含正確的 /v1。",
    http: (status: number) => `服務回應 HTTP ${status}，請檢查金鑰、權限或服務設定。`,
    model: (model: string) => `服務可連線，但找不到模型「${model}」。請確認模型 ID 已安裝或可用。`,
    certificate: "伺服器憑證未通過信任驗證（可能是自簽憑證）。澄境不會自行放行；請核對下方指紋後再手動信任。",
    certificateChanged: "憑證已更換：目前指紋與已儲存的信任指紋不同。澄境不會自動更新信任。",
    certificateExpired: "憑證已過期或尚未生效，請在伺服器更換有效憑證後再試。",
    certificateTlsFailed: "TLS 驗證失敗，請檢查憑證、系統時間與網路代理設定。",
    errorCode: "錯誤碼",
  },
  "zh-CN": {
    title: "连接诊断",
    healthy: (model: string) => `连接和模型正常：${model}`,
    url: "地址格式或安全规则不正确。",
    connection: "无法建立连接，请检查服务、IP、端口和防火墙。",
    apiPath: "服务已响应，但 API 路径不正确。请确认地址是否包含正确的 /v1。",
    http: (status: number) => `服务返回 HTTP ${status}，请检查密钥、权限或服务设置。`,
    model: (model: string) => `服务可连接，但找不到模型“${model}”。请确认模型 ID 已安装或可用。`,
    certificate: "服务器证书未通过信任验证（可能是自签名证书）。澄境不会自行放行；请核对下方指纹后再手动信任。",
    certificateChanged: "证书已更换：当前指纹与已保存的信任指纹不同。澄境不会自动更新信任。",
    certificateExpired: "证书已过期或尚未生效，请在服务器更换有效证书后重试。",
    certificateTlsFailed: "TLS 验证失败，请检查证书、系统时间和网络代理设置。",
    errorCode: "错误码",
  },
  en: {
    title: "Connection diagnostics",
    healthy: (model: string) => `Connection and model are ready: ${model}`,
    url: "The URL format or security policy is invalid.",
    connection: "Could not establish a connection. Check the service, IP, port, and firewall.",
    apiPath: "The service responded, but the API path is incorrect. Confirm that the URL includes the correct /v1 path.",
    http: (status: number) => `The service returned HTTP ${status}. Check the API key, permissions, or service settings.`,
    model: (model: string) => `The service is reachable, but model “${model}” was not found. Confirm that the model ID is installed or available.`,
    certificate: "The server certificate failed trust validation (it may be self-signed). ChengJing never bypasses TLS on its own; verify the fingerprint below before trusting it.",
    certificateChanged: "Certificate changed: the presented fingerprint differs from the saved trust. ChengJing will not update it automatically.",
    certificateExpired: "The certificate is expired or not yet valid. Replace it on the server and try again.",
    certificateTlsFailed: "TLS validation failed. Check the certificate, system clock, and network proxy settings.",
    errorCode: "Error code",
  },
  ja: {
    title: "接続診断",
    healthy: (model: string) => `接続とモデルは正常です：${model}`,
    url: "URL形式またはセキュリティ規則が正しくありません。",
    connection: "接続できません。サービス、IP、ポート、ファイアウォールを確認してください。",
    apiPath: "サービスは応答しましたが、APIパスが正しくありません。URLに正しい /v1 が含まれるか確認してください。",
    http: (status: number) => `サービスがHTTP ${status}を返しました。キー、権限、サービス設定を確認してください。`,
    model: (model: string) => `サービスには接続できますが、モデル「${model}」が見つかりません。モデルIDを確認してください。`,
    certificate: "サーバー証明書の信頼検証に失敗しました（自己署名の可能性があります）。澄境が独自に回避することはありません。下の指紋を確認してから信頼してください。",
    certificateChanged: "証明書が変更されました。提示された指紋が保存済みの信頼と異なるため、自動更新しません。",
    certificateExpired: "証明書の期限が切れているか、まだ有効ではありません。サーバーの証明書を更新して再試行してください。",
    certificateTlsFailed: "TLS検証に失敗しました。証明書、システム時刻、ネットワークプロキシを確認してください。",
    errorCode: "エラーコード",
  },
  ko: {
    title: "연결 진단",
    healthy: (model: string) => `연결과 모델이 정상입니다: ${model}`,
    url: "URL 형식 또는 보안 규칙이 올바르지 않습니다.",
    connection: "연결할 수 없습니다. 서비스, IP, 포트, 방화벽을 확인하세요.",
    apiPath: "서비스는 응답했지만 API 경로가 올바르지 않습니다. URL에 올바른 /v1이 포함되었는지 확인하세요.",
    http: (status: number) => `서비스가 HTTP ${status}를 반환했습니다. 키, 권한 또는 서비스 설정을 확인하세요.`,
    model: (model: string) => `서비스에는 연결되지만 모델 '${model}'을 찾을 수 없습니다. 모델 ID를 확인하세요.`,
    certificate: "서버 인증서 신뢰 검증에 실패했습니다(자체 서명일 수 있습니다). ChengJing이 임의로 우회하지 않습니다. 아래 지문을 확인한 뒤 신뢰하세요.",
    certificateChanged: "인증서가 변경되었습니다. 현재 지문이 저장된 신뢰 지문과 달라 자동으로 갱신하지 않습니다.",
    certificateExpired: "인증서가 만료되었거나 아직 유효하지 않습니다. 서버 인증서를 교체한 뒤 다시 시도하세요.",
    certificateTlsFailed: "TLS 검증에 실패했습니다. 인증서, 시스템 시간 및 네트워크 프록시를 확인하세요.",
    errorCode: "오류 코드",
  },
} as const;

export function getProviderDiagnosticCopy(language: AppLanguage) {
  return diagnosticCopy[language] || diagnosticCopy.en;
}

const apiModeCopy = {
  "zh-TW": { label: "API 模式", chat: "Chat Completions", chatHint: "相容範圍最廣", responses: "Responses API", responsesHint: "新式輸入與結構化輸出", privacy: "遠端 Responses 請求固定使用 store: false；Ollama 使用非狀態式模式。" },
  "zh-CN": { label: "API 模式", chat: "Chat Completions", chatHint: "兼容范围最广", responses: "Responses API", responsesHint: "新式输入与结构化输出", privacy: "远程 Responses 请求固定使用 store: false；Ollama 使用无状态模式。" },
  en: { label: "API mode", chat: "Chat Completions", chatHint: "Broadest compatibility", responses: "Responses API", responsesHint: "Modern input and structured output", privacy: "Remote Responses requests always use store: false; Ollama uses stateless mode." },
  ja: { label: "APIモード", chat: "Chat Completions", chatHint: "最も広い互換性", responses: "Responses API", responsesHint: "新しい入力と構造化出力", privacy: "リモートResponsesは常にstore: false、Ollamaはステートレスで使用します。" },
  ko: { label: "API 모드", chat: "Chat Completions", chatHint: "가장 넓은 호환성", responses: "Responses API", responsesHint: "최신 입력 및 구조화 출력", privacy: "원격 Responses 요청은 항상 store: false이며 Ollama는 비상태 모드로 사용합니다." },
} as const;

export function getProviderApiModeCopy(language: AppLanguage) { return apiModeCopy[language] || apiModeCopy.en; }

const certTrustCopy = {
  "zh-TW": {
    title: "信任這個伺服器憑證",
    warning: "系統不信任這個憑證，通常是自簽憑證。只有在你確認這是自己的 LiteLLM 或內部伺服器時才信任。",
    fingerprint: "憑證指紋（SHA-256）",
    storedFingerprint: "已儲存指紋",
    presentedFingerprint: "目前指紋",
    subject: "核發對象",
    issuer: "簽發者",
    validFrom: "生效時間",
    validTo: "有效期限",
    authorizationError: "系統驗證訊息",
    trust: "信任此憑證並重試",
    trusting: "正在信任…",
    trusted: "已信任這個憑證，僅限這個主機；換憑證或換主機就會失效。",
    badge: "已儲存憑證信任",
    connected: "連線成功，憑證與信任指紋相符。",
    changed: "憑證已更換，禁止自動更新信任。請核對新指紋後先撤銷舊信任，再重新測試。",
    expired: "憑證已過期或尚未生效，請更換伺服器憑證。",
    tlsFailed: "TLS 驗證失敗，以下為目前連線診斷資訊。",
    errorCode: "錯誤碼",
    revoke: "撤銷憑證信任",
    unavailable: "讀取憑證失敗，請確認服務已啟動後再測一次。",
    mismatch: "指紋與伺服器目前出示的憑證不同，請重新核對。",
  },
  "zh-CN": {
    title: "信任这个服务器证书",
    warning: "系统不信任这个证书，通常是自签名证书。只有在你确认这是自己的 LiteLLM 或内部服务器时才信任。",
    fingerprint: "证书指纹（SHA-256）",
    storedFingerprint: "已保存指纹",
    presentedFingerprint: "当前指纹",
    subject: "颁发对象",
    issuer: "签发者",
    validFrom: "生效时间",
    validTo: "有效期至",
    authorizationError: "系统验证信息",
    trust: "信任此证书并重试",
    trusting: "正在信任…",
    trusted: "已信任这个证书，仅限这台主机；更换证书或主机后失效。",
    badge: "已保存证书信任",
    connected: "连接成功，证书与信任指纹一致。",
    changed: "证书已更换，禁止自动更新信任。请核对新指纹后先撤销旧信任，再重新测试。",
    expired: "证书已过期或尚未生效，请更换服务器证书。",
    tlsFailed: "TLS 验证失败，以下是当前连接诊断信息。",
    errorCode: "错误码",
    revoke: "撤销证书信任",
    unavailable: "读取证书失败，请确认服务已启动后重试。",
    mismatch: "指纹与服务器当前出示的证书不同，请重新核对。",
  },
  en: {
    title: "Trust this server certificate",
    warning: "Your system does not trust this certificate, usually because it is self-signed. Trust it only if you confirm this is your own LiteLLM or internal server.",
    fingerprint: "Certificate fingerprint (SHA-256)",
    storedFingerprint: "Saved fingerprint",
    presentedFingerprint: "Presented fingerprint",
    subject: "Issued to",
    issuer: "Issuer",
    validFrom: "Valid from",
    validTo: "Valid until",
    authorizationError: "System validation",
    trust: "Trust certificate and retry",
    trusting: "Trusting…",
    trusted: "Certificate trusted for this host only. It stops working if the certificate or host changes.",
    badge: "Certificate trust saved",
    connected: "Connection succeeded and the certificate matches the saved fingerprint.",
    changed: "Certificate changed. Automatic trust updates are blocked. Revoke the old trust, verify the new fingerprint, and test again.",
    expired: "The certificate is expired or not yet valid. Replace the server certificate.",
    tlsFailed: "TLS validation failed. The current connection diagnostics are shown below.",
    errorCode: "Error code",
    revoke: "Revoke certificate trust",
    unavailable: "Could not read the certificate. Confirm the service is running and test again.",
    mismatch: "The fingerprint differs from the certificate the server is presenting now. Please re-verify.",
  },
  ja: {
    title: "このサーバー証明書を信頼する",
    warning: "この証明書はシステムに信頼されていません。自己署名の可能性があります。自分のLiteLLMや社内サーバーだと確認できた場合のみ信頼してください。",
    fingerprint: "証明書指紋（SHA-256）",
    storedFingerprint: "保存済み指紋",
    presentedFingerprint: "現在の指紋",
    subject: "対象",
    issuer: "発行者",
    validFrom: "有効開始",
    validTo: "有効期限",
    authorizationError: "システム検証情報",
    trust: "証明書を信頼して再試行",
    trusting: "信頼設定中…",
    trusted: "このホストに限り証明書を信頼しました。証明書またはホストが変わると無効になります。",
    badge: "証明書の信頼を保存済み",
    connected: "接続に成功し、証明書の指紋が保存済みのものと一致しました。",
    changed: "証明書が変更されています。自動更新はしません。古い信頼を取り消し、新しい指紋を確認して再試行してください。",
    expired: "証明書の期限が切れているか、まだ有効ではありません。サーバー証明書を更新してください。",
    tlsFailed: "TLS検証に失敗しました。現在の接続診断を表示しています。",
    errorCode: "エラーコード",
    revoke: "証明書の信頼を取り消す",
    unavailable: "証明書を読み取れませんでした。サービスが起動しているか確認して再テストしてください。",
    mismatch: "指紋がサーバーが現在提示している証明書と異なります。もう一度確認してください。",
  },
  ko: {
    title: "이 서버 인증서 신뢰",
    warning: "이 인증서는 시스템에서 신뢰하지 않습니다(자체 서명일 수 있습니다). 자신의 LiteLLM 또는 내부 서버임을 확인한 경우에만 신뢰하세요.",
    fingerprint: "인증서 지문(SHA-256)",
    storedFingerprint: "저장된 지문",
    presentedFingerprint: "현재 지문",
    subject: "발급 대상",
    issuer: "발급자",
    validFrom: "유효 시작",
    validTo: "만료일",
    authorizationError: "시스템 검증 정보",
    trust: "인증서 신뢰 후 재시도",
    trusting: "신뢰 설정 중…",
    trusted: "이 호스트에 대해서만 인증서를 신뢰했습니다. 인증서 또는 호스트가 바뀌면 해제됩니다.",
    badge: "인증서 신뢰 저장됨",
    connected: "연결에 성공했고 인증서 지문이 저장된 지문과 일치합니다.",
    changed: "인증서가 변경되었습니다. 자동 신뢰 갱신을 차단했습니다. 기존 신뢰를 해제하고 새 지문을 확인한 뒤 다시 테스트하세요.",
    expired: "인증서가 만료되었거나 아직 유효하지 않습니다. 서버 인증서를 교체하세요.",
    tlsFailed: "TLS 검증에 실패했습니다. 현재 연결 진단을 표시합니다.",
    errorCode: "오류 코드",
    revoke: "인증서 신뢰 해제",
    unavailable: "인증서를 읽을 수 없습니다. 서비스가 실행 중인지 확인한 뒤 다시 테스트하세요.",
    mismatch: "지문이 서버가 현재 제시하는 인증서와 다릅니다. 다시 확인해 주세요.",
  },
} as const;

export function getProviderCertTrustCopy(language: AppLanguage) {
  return certTrustCopy[language] || certTrustCopy.en;
}

/** 將 64 字元 SHA-256 hex 整理成 AA:BB:CC… 給使用者核對；不合法時回傳空字串。 */
export function formatCertFingerprint(value?: string): string {
  const hex = String(value ?? "").toUpperCase().replace(/[^0-9A-F]/g, "");
  return hex.length === 64 ? hex.match(/.{2}/g)!.join(":") : "";
}
