import type { AppLanguage } from "../types";

const copy = {
  "zh-TW": {
    eyebrow: "附件健康",
    title: "附件健康中心",
    description: "檢查卡片、正文與歷史版本中的附件引用，只清理確定沒有任何引用的孤兒附件。",
    scan: "重新檢查",
    scanning: "檢查中…",
    cleanup: "清理孤兒附件",
    cleaning: "清理中…",
    cleanDone: (count: number) => `已清理 ${count} 個孤兒附件。`,
    cleanFailed: (count: number) => `有 ${count} 個附件清理失敗，資料未自動刪除。`,
    empty: "目前沒有發現附件問題。",
    total: (count: number) => `共 ${count} 個附件`,
    referenced: (count: number) => `${count} 個有引用`,
    orphaned: (count: number) => `${count} 個孤兒`,
    issues: (count: number) => `${count} 個問題`,
    bytes: (value: string) => `${value} 已儲存`,
    orphan: "沒有卡片或歷史版本引用",
    missingBlob: "IndexedDB 內容遺失",
    missingPath: "檔案附件缺少相對路徑",
    unreadable: "本機檔案無法讀取",
    sizeMismatch: "記錄大小與實際內容不一致",
    invalidSha: "SHA-256 格式無效",
  },
  "zh-CN": {
    eyebrow: "附件健康",
    title: "附件健康中心",
    description: "检查卡片、正文和历史版本中的附件引用，只清理确定没有任何引用的孤儿附件。",
    scan: "重新检查",
    scanning: "检查中…",
    cleanup: "清理孤儿附件",
    cleaning: "清理中…",
    cleanDone: (count: number) => `已清理 ${count} 个孤儿附件。`,
    cleanFailed: (count: number) => `${count} 个附件清理失败，数据未自动删除。`,
    empty: "目前没有发现附件问题。",
    total: (count: number) => `共 ${count} 个附件`,
    referenced: (count: number) => `${count} 个有引用`,
    orphaned: (count: number) => `${count} 个孤儿`,
    issues: (count: number) => `${count} 个问题`,
    bytes: (value: string) => `${value} 已存储`,
    orphan: "没有卡片或历史版本引用",
    missingBlob: "IndexedDB 内容丢失",
    missingPath: "文件附件缺少相对路径",
    unreadable: "本地文件无法读取",
    sizeMismatch: "记录大小与实际内容不一致",
    invalidSha: "SHA-256 格式无效",
  },
  en: {
    eyebrow: "Attachment health",
    title: "Attachment health center",
    description: "Check attachment references in cards, content, and history. Only attachments with no reference are eligible for cleanup.",
    scan: "Scan again",
    scanning: "Scanning…",
    cleanup: "Clean orphan attachments",
    cleaning: "Cleaning…",
    cleanDone: (count: number) => `Cleaned ${count} orphan attachment${count === 1 ? "" : "s"}.`,
    cleanFailed: (count: number) => `${count} attachment cleanup${count === 1 ? "" : "s"} failed; nothing else was removed.`,
    empty: "No attachment problems found.",
    total: (count: number) => `${count} attachment${count === 1 ? "" : "s"}`,
    referenced: (count: number) => `${count} referenced`,
    orphaned: (count: number) => `${count} orphaned`,
    issues: (count: number) => `${count} issue${count === 1 ? "" : "s"}`,
    bytes: (value: string) => `${value} stored`,
    orphan: "Not referenced by a card or history",
    missingBlob: "IndexedDB content is missing",
    missingPath: "File attachment has no relative path",
    unreadable: "Local file could not be read",
    sizeMismatch: "Recorded size differs from content",
    invalidSha: "Invalid SHA-256 value",
  },
  ja: {
    eyebrow: "添付ファイルの状態",
    title: "添付ファイルの状態センター",
    description: "カード、本文、履歴の参照を確認します。どこからも参照されていない添付ファイルだけを整理できます。",
    scan: "再チェック",
    scanning: "チェック中…",
    cleanup: "孤立した添付を整理",
    cleaning: "整理中…",
    cleanDone: (count: number) => `${count} 件の孤立した添付を整理しました。`,
    cleanFailed: (count: number) => `${count} 件の整理に失敗しました。他のデータは削除していません。`,
    empty: "添付ファイルの問題は見つかりませんでした。",
    total: (count: number) => `添付 ${count} 件`,
    referenced: (count: number) => `参照あり ${count} 件`,
    orphaned: (count: number) => `孤立 ${count} 件`,
    issues: (count: number) => `問題 ${count} 件`,
    bytes: (value: string) => `${value} 保存済み`,
    orphan: "カードまたは履歴から参照されていません",
    missingBlob: "IndexedDB の内容がありません",
    missingPath: "ファイル添付に相対パスがありません",
    unreadable: "ローカルファイルを読み取れません",
    sizeMismatch: "記録サイズと内容が一致しません",
    invalidSha: "SHA-256 の形式が無効です",
  },
  ko: {
    eyebrow: "첨부 파일 상태",
    title: "첨부 파일 상태 센터",
    description: "카드, 본문, 기록의 첨부 파일 참조를 확인합니다. 어디에서도 참조하지 않는 고아 첨부만 정리할 수 있습니다.",
    scan: "다시 검사",
    scanning: "검사 중…",
    cleanup: "고아 첨부 정리",
    cleaning: "정리 중…",
    cleanDone: (count: number) => `고아 첨부 ${count}개를 정리했습니다.`,
    cleanFailed: (count: number) => `${count}개 첨부 정리에 실패했습니다. 다른 데이터는 삭제하지 않았습니다.`,
    empty: "첨부 파일 문제가 발견되지 않았습니다.",
    total: (count: number) => `첨부 ${count}개`,
    referenced: (count: number) => `참조됨 ${count}개`,
    orphaned: (count: number) => `고아 ${count}개`,
    issues: (count: number) => `문제 ${count}개`,
    bytes: (value: string) => `${value} 저장됨`,
    orphan: "카드나 기록에서 참조되지 않음",
    missingBlob: "IndexedDB 내용이 없음",
    missingPath: "파일 첨부의 상대 경로가 없음",
    unreadable: "로컬 파일을 읽을 수 없음",
    sizeMismatch: "기록된 크기와 내용이 다름",
    invalidSha: "SHA-256 값이 올바르지 않음",
  },
} as const;

export function getAttachmentHealthCopy(language: AppLanguage) {
  return copy[language] || copy.en;
}
