import type { AppLanguage } from "../types";

const copy = {
  "zh-TW": {
    eyebrow: "附件健康",
    title: "附件健康中心",
    description: "檢查卡片、正文與歷史版本中的附件引用，只清理確定沒有任何引用的孤兒附件。",
    scan: "重新檢查",
    scanning: "檢查中…",
    cleanup: "清理孤兒附件",
    cleaning: "清理中…",
    cleanDone: (count: number) => `已清理 ${count} 個孤兒附件。`,
    cleanFailed: (count: number) => `有 ${count} 個附件清理失敗，資料未自動刪除。`,
    empty: "目前沒有發現附件問題。",
    total: (count: number) => `共 ${count} 個附件`,
    referenced: (count: number) => `${count} 個有引用`,
    orphaned: (count: number) => `${count} 個孤兒`,
    issues: (count: number) => `${count} 個問題`,
    bytes: (value: string) => `${value} 已儲存`,
    role: { source: "來源文件", inline: "內嵌圖片", attachment: "一般附件" },
    storageFile: "附件檔案",
    storageIndexedDb: "資料庫",
    filterAll: "全部",
    filterIssues: "有問題",
    filterOrphaned: "孤兒",
    filterSource: "來源",
    filterInline: "內嵌圖片",
    filterAttachment: "一般附件",
    searchPlaceholder: "搜尋檔名、類型或附件 ID",
    showing: (visible: number, total: number) => `顯示 ${visible} / ${total}`,
    noMatches: "沒有符合條件的附件。",
    details: "詳細資料",
    id: "附件 ID",
    path: "儲存路徑",
    referenceCount: (count: number) => `${count} 個引用`,
    copyReference: "複製附件引用",
    copiedReference: "附件引用已複製。",
    copyFailed: "無法複製附件引用。",
    download: "下載附件",
    downloading: "下載中…",
    downloaded: (name: string) => `已下載「${name}」。`,
    downloadFailed: "附件內容目前無法讀取。",
    orphan: "沒有卡片或歷史版本引用",
    missingBlob: "IndexedDB 內容遺失",
    missingPath: "檔案附件缺少相對路徑",
    unreadable: "本機檔案無法讀取",
    sizeMismatch: "記錄大小與實際內容不一致",
    invalidSha: "SHA-256 格式無效",
  },
  "zh-CN": {
    eyebrow: "附件健康",
    title: "附件健康中心",
    description: "检查卡片、正文和历史版本中的附件引用，只清理确定没有任何引用的孤儿附件。",
    scan: "重新检查",
    scanning: "检查中…",
    cleanup: "清理孤儿附件",
    cleaning: "清理中…",
    cleanDone: (count: number) => `已清理 ${count} 个孤儿附件。`,
    cleanFailed: (count: number) => `${count} 个附件清理失败，数据未自动删除。`,
    empty: "目前没有发现附件问题。",
    total: (count: number) => `共 ${count} 个附件`,
    referenced: (count: number) => `${count} 个有引用`,
    orphaned: (count: number) => `${count} 个孤儿`,
    issues: (count: number) => `${count} 个问题`,
    bytes: (value: string) => `${value} 已存储`,
    role: { source: "来源文件", inline: "内嵌图片", attachment: "一般附件" },
    storageFile: "附件文件",
    storageIndexedDb: "数据库",
    filterAll: "全部",
    filterIssues: "有问题",
    filterOrphaned: "孤儿",
    filterSource: "来源",
    filterInline: "内嵌图片",
    filterAttachment: "一般附件",
    searchPlaceholder: "搜索文件名、类型或附件 ID",
    showing: (visible: number, total: number) => `显示 ${visible} / ${total}`,
    noMatches: "没有符合条件的附件。",
    details: "详细资料",
    id: "附件 ID",
    path: "存储路径",
    referenceCount: (count: number) => `${count} 个引用`,
    copyReference: "复制附件引用",
    copiedReference: "附件引用已复制。",
    copyFailed: "无法复制附件引用。",
    download: "下载附件",
    downloading: "下载中…",
    downloaded: (name: string) => `已下载“${name}”。`,
    downloadFailed: "附件内容目前无法读取。",
    orphan: "没有卡片或历史版本引用",
    missingBlob: "IndexedDB 内容丢失",
    missingPath: "文件附件缺少相对路径",
    unreadable: "本地文件无法读取",
    sizeMismatch: "记录大小与实际内容不一致",
    invalidSha: "SHA-256 格式无效",
  },
  en: {
    eyebrow: "Attachment health",
    title: "Attachment health center",
    description: "Check attachment references in cards, content, and history. Only attachments with no reference are eligible for cleanup.",
    scan: "Scan again",
    scanning: "Scanning…",
    cleanup: "Clean orphan attachments",
    cleaning: "Cleaning…",
    cleanDone: (count: number) => `Cleaned ${count} orphan attachment${count === 1 ? "" : "s"}.`,
    cleanFailed: (count: number) => `${count} attachment cleanup${count === 1 ? "" : "s"} failed; nothing else was removed.`,
    empty: "No attachment problems found.",
    total: (count: number) => `${count} attachment${count === 1 ? "" : "s"}`,
    referenced: (count: number) => `${count} referenced`,
    orphaned: (count: number) => `${count} orphaned`,
    issues: (count: number) => `${count} issue${count === 1 ? "" : "s"}`,
    bytes: (value: string) => `${value} stored`,
    role: { source: "Source document", inline: "Inline image", attachment: "Attachment" },
    storageFile: "Attachment file",
    storageIndexedDb: "Database",
    filterAll: "All",
    filterIssues: "Issues",
    filterOrphaned: "Orphaned",
    filterSource: "Sources",
    filterInline: "Inline images",
    filterAttachment: "Attachments",
    searchPlaceholder: "Search name, type, or attachment ID",
    showing: (visible: number, total: number) => `Showing ${visible} of ${total}`,
    noMatches: "No attachments match these filters.",
    details: "Details",
    id: "Attachment ID",
    path: "Storage path",
    referenceCount: (count: number) => `${count} reference${count === 1 ? "" : "s"}`,
    copyReference: "Copy attachment reference",
    copiedReference: "Attachment reference copied.",
    copyFailed: "Could not copy the attachment reference.",
    download: "Download attachment",
    downloading: "Downloading…",
    downloaded: (name: string) => `Downloaded “${name}”.`,
    downloadFailed: "The attachment content is not readable right now.",
    orphan: "Not referenced by a card or history",
    missingBlob: "IndexedDB content is missing",
    missingPath: "File attachment has no relative path",
    unreadable: "Local file could not be read",
    sizeMismatch: "Recorded size differs from content",
    invalidSha: "Invalid SHA-256 value",
  },
  ja: {
    eyebrow: "添付ファイルの状態",
    title: "添付ファイルの状態センター",
    description: "カード、本文、履歴の参照を確認します。どこからも参照されていない添付ファイルだけを整理できます。",
    scan: "再チェック",
    scanning: "チェック中…",
    cleanup: "孤立した添付を整理",
    cleaning: "整理中…",
    cleanDone: (count: number) => `${count} 件の孤立した添付を整理しました。`,
    cleanFailed: (count: number) => `${count} 件の整理に失敗しました。他のデータは削除していません。`,
    empty: "添付ファイルの問題は見つかりませんでした。",
    total: (count: number) => `添付 ${count} 件`,
    referenced: (count: number) => `参照あり ${count} 件`,
    orphaned: (count: number) => `孤立 ${count} 件`,
    issues: (count: number) => `問題 ${count} 件`,
    bytes: (value: string) => `${value} 保存済み`,
    role: { source: "元ファイル", inline: "本文内画像", attachment: "添付ファイル" },
    storageFile: "添付ファイル",
    storageIndexedDb: "データベース",
    filterAll: "すべて",
    filterIssues: "問題あり",
    filterOrphaned: "孤立",
    filterSource: "元ファイル",
    filterInline: "本文内画像",
    filterAttachment: "添付",
    searchPlaceholder: "ファイル名、種類、添付 ID を検索",
    showing: (visible: number, total: number) => `${visible} / ${total} 件を表示`,
    noMatches: "条件に一致する添付ファイルはありません。",
    details: "詳細",
    id: "添付 ID",
    path: "保存先パス",
    referenceCount: (count: number) => `参照 ${count} 件`,
    copyReference: "添付の参照をコピー",
    copiedReference: "添付の参照をコピーしました。",
    copyFailed: "添付の参照をコピーできませんでした。",
    download: "添付をダウンロード",
    downloading: "ダウンロード中…",
    downloaded: (name: string) => `「${name}」をダウンロードしました。`,
    downloadFailed: "添付ファイルの内容を読み取れません。",
    orphan: "カードまたは履歴から参照されていません",
    missingBlob: "IndexedDB の内容がありません",
    missingPath: "ファイル添付に相対パスがありません",
    unreadable: "ローカルファイルを読み取れません",
    sizeMismatch: "記録サイズと内容が一致しません",
    invalidSha: "SHA-256 の形式が無効です",
  },
  ko: {
    eyebrow: "첨부 파일 상태",
    title: "첨부 파일 상태 센터",
    description: "카드, 본문, 기록의 첨부 파일 참조를 확인합니다. 어디에서도 참조하지 않는 고아 첨부만 정리할 수 있습니다.",
    scan: "다시 검사",
    scanning: "검사 중…",
    cleanup: "고아 첨부 정리",
    cleaning: "정리 중…",
    cleanDone: (count: number) => `고아 첨부 ${count}개를 정리했습니다.`,
    cleanFailed: (count: number) => `${count}개 첨부 정리에 실패했습니다. 다른 데이터는 삭제하지 않았습니다.`,
    empty: "첨부 파일 문제가 발견되지 않았습니다.",
    total: (count: number) => `첨부 ${count}개`,
    referenced: (count: number) => `참조됨 ${count}개`,
    orphaned: (count: number) => `고아 ${count}개`,
    issues: (count: number) => `문제 ${count}개`,
    bytes: (value: string) => `${value} 저장됨`,
    role: { source: "원본 문서", inline: "본문 이미지", attachment: "일반 첨부" },
    storageFile: "첨부 파일",
    storageIndexedDb: "데이터베이스",
    filterAll: "전체",
    filterIssues: "문제 있음",
    filterOrphaned: "고아",
    filterSource: "원본",
    filterInline: "본문 이미지",
    filterAttachment: "첨부",
    searchPlaceholder: "파일명, 형식 또는 첨부 ID 검색",
    showing: (visible: number, total: number) => `${total}개 중 ${visible}개 표시`,
    noMatches: "조건에 맞는 첨부 파일이 없습니다.",
    details: "상세 정보",
    id: "첨부 ID",
    path: "저장 경로",
    referenceCount: (count: number) => `참조 ${count}개`,
    copyReference: "첨부 참조 복사",
    copiedReference: "첨부 참조를 복사했습니다.",
    copyFailed: "첨부 참조를 복사하지 못했습니다.",
    download: "첨부 다운로드",
    downloading: "다운로드 중…",
    downloaded: (name: string) => `“${name}”을(를) 다운로드했습니다.`,
    downloadFailed: "현재 첨부 파일 내용을 읽을 수 없습니다.",
    orphan: "카드나 기록에서 참조되지 않음",
    missingBlob: "IndexedDB 내용이 없음",
    missingPath: "파일 첨부의 상대 경로가 없음",
    unreadable: "로컬 파일을 읽을 수 없음",
    sizeMismatch: "기록된 크기와 내용이 다름",
    invalidSha: "SHA-256 값이 올바르지 않음",
  },
} as const;

export function getAttachmentHealthCopy(language: AppLanguage) {
  return copy[language] || copy.en;
}
